### ISSUE TITLE
Are the source files for the ico and logo files available?

### ISSUE THREAD

**Issue by eshellman** [gutenbergtools/gutenbergsite#24]
see https://github.com/openzim/gutenberg/issues/165

**Comment by eshellman** [comment]
I also asked the social media list if the avatars for FB/Twitter/?? need refreshing

**Comment by benoit74** [comment]
Is there any news you could share on this topic? 

Otherwise we will soon proceed with the provided file, but it would be better if we could use an online version so that any change you make to your logo would be reflected in the ZIM.

And as mentioned, it would be great to have higher (512x512) resolutions, or at least 192x192.

We can live without all that, this comment is more on gentle reminder so that we do not move forward on our own while you are making progress on your side in parallel as well.

**Comment by gbnewby** [comment]
[current.zip](https://github.com/gbnewby/gutenbergsite/files/12381406/current.zip)

I didn't know someone was waiting for this. The PPTX was what was used to make the various derived formats, so if you need a specific resolution or shape that is your starting point.

I'm not really a designer, as you can see from this collection. If you (Benoit) or someone else has expertise to make some updated formats, definitely we can get those onto the site and make them available for distribution. Confirmed that the image is of an Albion printing press, taken from the 1913 Encyclopedia Britannica. 

If nobody following this thread or the OpenZIM one seems to have capability and/or capacity to make the desired images, but could post some specific guidance (not just a set of links to various websites), I could try to find a volunteer to help. Thanks for pursuing this. It seems worthwhile to get the images including favicon updated.

**Comment by benoit74** [comment]
Thank you very much for the source!

It looks like you use Harrington font for the P and G letters, do you confirm?

If yes, unfortunately from what I see (e.g. [here](https://www.dafontfree.co/harrington-font/)), the font is free only for personal use. Did you get authorization from the font creator to use it for your project and we (OpenZim) might benefit from it too ? 

Or did you used another version of this font (because I'm not 100% sure I found the proper version of the font), or another font ?

**Comment by gbnewby** [comment]
Hi Benoit.

Yes, that is Harrington. It's part of the standard Microsoft Office suite.

I chose Harrington specifically because it is in the public domain in the
US based on its age.

I see the bogus copyright claim on the site you linked, and Microsoft has a
similar bogus claim (
https://learn.microsoft.com/en-us/typography/font-list/harrington).
Creating glyphs from a font is "sweat of the brow," not authorship, and is
therefore not eligible for a US copyright. See the "no sweat of the brow
copyright" how-to at www.gutenberg.org for more on this.

It's easy to find Harrington in font catalog entries from back then. For
example, here: http://luc.devroye.org/fonts-44010.html

If you know of a suitable font that doesn't suffer from bogus copyright
claims, I would certainly consider using it.

**Comment by benoit74** [comment]
If it is OK for you in terms of licensing, then I really don't mind to continue using Harrington. I was just worried by the copyright claims I found on the web and preferred to ask rather than be sorry later.

**Comment by gbnewby** [comment]
It looks like this should have been closed awhile ago...
